# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=512)),
                ('player_alias', models.CharField(blank=True, max_length=256)),
                ('player_URL', models.CharField(max_length=1024)),
                ('player_seed', models.CharField(max_length=3)),
                ('player_img', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=256)),
                ('tournament_location', models.CharField(default=False, max_length=256)),
                ('tournament_start_date', models.DateField()),
                ('tournament_category', models.CharField(max_length=100)),
                ('tournament_surface', models.CharField(max_length=256)),
                ('tournament_draw', models.CharField(max_length=10)),
                ('tournament_popularity', models.BooleanField(default=False)),
            ],
        ),
    ]
