# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tennis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_nid', models.CharField(max_length=512)),
                ('match_hour', models.CharField(max_length=100)),
                ('match_round', models.CharField(max_length=100)),
                ('player1_set1', models.IntegerField()),
                ('player1_set2', models.IntegerField()),
                ('player1_set3', models.IntegerField()),
                ('player1_set4', models.IntegerField()),
                ('player1_set5', models.IntegerField()),
                ('player2_set1', models.IntegerField()),
                ('player2_set2', models.IntegerField()),
                ('player2_set3', models.IntegerField()),
                ('player2_set4', models.IntegerField()),
                ('player2_set5', models.IntegerField()),
                ('player1_setTotal', models.IntegerField()),
                ('player2_setTotal', models.IntegerField()),
                ('total_games', models.IntegerField()),
                ('player1', models.ManyToManyField(related_name='player1', to='Tennis.Player')),
                ('player2', models.ManyToManyField(related_name='player2', to='Tennis.Player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tennis.Tournament')),
            ],
        ),
    ]
